.github/workflows/build.yml
.github/workflows/gitlab-ci.yml
.github/workflows/lint.yml

* Add `pull_request` and `workflow_dispatch` triggers on our CI except docker tasks.
* Run on all branches, not just `main`.
* The `gitlab-ci` workflow will no longer trigger on `delete`.

ci: Improve workflow triggers

---

.github/workflows/build.yml
.github/workflows/gitlab-ci.yml

Use the new `riscv-gcc-install` action from `pulp-actions` to install the RISC-V GCC toolchain in CI. It also ensures CI is skipped on forks or pull requests from forks due to missing secrets.

ci: Use `riscv-gcc-install` PULP action

---

target/xilinx/constraints/cheshire.xdc
target/xilinx/src/cheshire_top_xilinx.sv

* Fix `RtcFreq` parameter provided to SoC.
* Fix `test_mode_i` pin and MIG false paths in constraints.

target/xilinx: Fixes to top level and constraints

---

hw/cheshire_pkg.sv
hw/cheshire_soc.sv

This previously mapped _all_ LLC accesses to its cached SPM region, breaking DRAM access.

hw: Fix cached LLC SPM remapping

---

hw/cheshire_pkg.sv
hw/cheshire_soc.sv
hw/rv_plic.cfg.hjson
sw/boot/cheshire.dts

* Limit IRQs in default config to those mapped.
* Speed up MMC in device tree to maximum speed of 25 MHz.

hw: No ext IRQs by default, speed up MMC

---

.gitignore
Makefile
cheshire.mk
sw/sw.mk

* Dependencies (Bender and submodules) are only fetched once unless cleaned with `chs-clean-deps`
* Use immediate evaluation (`:=`) in various places to accelerate evaluation
* Avoid calling `shell bender path` as much as possible, adopting sub-dependency variable names where possible
* Enable parallel build (assuming no chained phonies)
* Scope some unscoped targets and variables with `chs` prefix

make: Optimize runtime, various fixes

---

Bender.lock
Bender.yml
hw/cheshire_soc.sv
target/sim/src/fixture_cheshire_soc.sv
target/sim/src/vip_cheshire_soc.sv

In the `vip`, add mutiple virtual AXI drivers to drive the serial link

target/sim: Add external serial link AXI port to VIP

---

Bender.lock
Bender.yml
hw/cheshire_pkg.sv
hw/cheshire_soc.sv
target/xilinx/scripts/run.tcl
target/xilinx/src/cheshire_top_xilinx.sv

Instantiate a parametric number of cva6 cores and corresponding CLICs. Self-invalidation coherence is provided by the version bumps of cva6 (`pulp-v0.4.0`) and the AXI AMO adapter (`v0.8.0`). Note: this does not augment the software stack for multicore (ZSBL etc.)

cva6: Add multicore support

---

hw/cheshire_soc.sv

Previously, all cores were connected to CLIC 0. Fix this by connecting each core to its dedicated CLIC line.

hw: Connect CLIC IRQs to corresponding cores

---

Bender.lock
Bender.yml

This version fixes a critical bug.

deps: Bump `axi_riscv_atomics` to v0.8.1

---

target/sim/src/tb_cheshire_soc.sv
target/sim/src/vip_cheshire_soc.sv

Wait until the current byte has been transmitted before terminating the simulation. This is bound by the UART baud period x bauds per byte.
Tested in carfield (which does not cover `tb_cheshire_soc`)

tb: Defer sim termination until UART transfer is complete

---

hw/cheshire_pkg.sv
hw/cheshire_soc.sv

When integrating multicore support into Cheshire, the AMO user bits were not made unique for each core. This MR fixes this.

hw: Fix AMO user IDs for cores

---

Makefile
cheshire.mk

To avoid a checkout of dependencies within the serial_link, setting the bender directory with -d allows for re-use of available dependencies.

Enforce bender directory to avoid extra checkout

---

hw/cheshire_pkg.sv

* This PR fixes the regbus address map, with the CLIC currently inaccessible
* Verified with an [access test in carfield](https://github.com/pulp-platform/carfield/blob/main/sw/tests/bare-metal/hostd/vclic_basic.c)
@bluewww

hw: Fix Regbus address range in AXI crossbar

---

sw/boot/zsl.c
sw/include/params.h
sw/lib/hal/uart_debug.c
sw/tests/helloworld.c

This avoids a replicated literal for the default boot baudrate (115200).

sw: Add parameter for default boot baudrate

---

Bender.lock
Bender.yml

Adding support for atomics, see https://github.com/pulp-platform/unbent/pull/2

deps: Update `unbent` to v0.1.6

---

Bender.lock
Bender.yml

This version contains critical bugfixes, see https://github.com/pulp-platform/axi_riscv_atomics/blob/v0.8.2/CHANGELOG.md
Investigating the failing CI right now.

deps: Update `axi_riscv_atomics` to v0.8.2

---

cheshire.mk
docs/tg/xilinx.md
sw/sw.mk

Fixes some build oversights and addresses the documentation shortcomings from #92.

treewide: Various build and documentation fixes

---

target/sim/src/vip_cheshire_soc.sv

First of three steps to merge back features/bugfixes from Carfield project. This is a testbench/simulation-only feature.
Remaining two steps (RTL features) are #102 and #74, to be addressed later

target/sim: Add JTAG tasks for reg access and preloading

---

Bender.lock
Bender.yml
docs/um/arch.md
hw/cheshire_pkg.sv
hw/cheshire_soc.sv

* Updates Bender IPs to latest versions.
* Updates `axi_vga` to new version fixing critical performance issue.
* Adds new propagated parameters based on this.

hw: Update `axi_vga` to fix performance issue

---

hw/cheshire_pkg.sv

This PR disables `FP8ALT` support in Cheshire so that the only floating-point formats supported in the CVA6 FPU are `FP64` and `FP32`.

hw: Disable CVA6 `FP8ALT` support

---

cheshire.mk

If Cheshire is used in another project (like Iguana/Basilisk), this line will fail to find `xilinx.mk` since the current working directory is not the root of Cheshire.

make: Ensure correct path to `xilinx.mk`

---

target/xilinx/src/cheshire_top_xilinx.sv

Fix a typo in the `reg_rsp_t` parameter. This is not very critical as it isn't used, but perhaps it can prevent future headaches.

target/xilinx: Fix typo in type parameter

---

hw/cheshire_pkg.sv

Unsized integer literals are guaranteed at most to be 32 bits wide, so any literals that must be guaranteed to be wider need an explicit width.

hw: Fix widths of `doub_bt` parameter literals

---

target/xilinx/xilinx.mk

target/xilinx: Remove quotes on `tclargs`

---

target/sim/src/vip_cheshire_soc.sv

Currently, printing empty lines (back-to-back `\n`s) causes Questasim to crash while attempting to stream the empty `uart_read_buf`. Fix this by checking if `uart_read_buf` is empty.

target/sim: Correctly handle empty UART lines

---

Makefile
cheshire.mk
docs/gs.md
docs/tg/xilinx.md
target/xilinx/xilinx.mk

* Explicitly collect phonies in `CHS_PHONY`:
* cleaner approach
* fixes tricky issues with recursive make invocation
* Provides a list of defined phonies through `make help`
* Documents tool paths used (Fixes #130).

make: Formalize phonies and document tool path vars

---

hw/cheshire_pkg.sv

Slang says:
`error: assignment pattern target type cannot be deduced in this context`
According to the spec chapter 6.24.1 the parenthesis around the expression to be casted are necessary.
This fixes the slang error.

hw: Add missing cast in ambiguous default expression

---

Bender.lock
Bender.yml

This PR reverts the AXI version from `0.39.4` to `0.39.3` due to the yanking of the former.

Downgrade AXI version because of yanking of 0.39.4

---

hw/cheshire_soc.sv

The equality operator `==` has precedence over the bitwise and operator `&` .

hw: Fix uncached SPM accessibility

---

sw/link/dram.ld
sw/link/rom.ld
sw/link/spm.ld

Under some conditions, `__bss_start` and `__bss_end` would not correctly delimit `.bss`.

sw/link: Avoid incorrect `.bss` delimiters

---

Bender.lock
Bender.yml
cheshire.mk
hw/cheshire_idma_wrap.sv
hw/cheshire_soc.sv
requirements.txt
sw/include/dif/dma.h
sw/include/regs/idma.h
sw/sw.mk
sw/tests/dma_2d.c
target/xilinx/xilinx.mk

* Update iDMA to `v0.6.3`, including wrapper removed upstream here.
* Add `dma_2d` test.
* Add `CHS_BENDER_RTL_FLAGS` as common source of RTL Bender flags.

hw: Update iDMA to `v0.6.3`

---

.github/workflows/lint.yml
Bender.lock
Bender.yml
Makefile
cheshire.mk
requirements.txt
sw/include/params.h
sw/include/regs/axi_rt.h
sw/include/util.h
sw/tests/axirt_budget.c
sw/tests/axirt_budget_isolate.c
sw/tests/axirt_hello.c
sw/tests/dma_2d.c

* Bump AXI-REALM to latest version. Fixes functional bug in the write buffer module (https://github.com/pulp-platform/axi_rt/pull/11).
* Fix default number of configuration registers in `cheshire.mk`
* Fix budget (W/R) left check in `axirt_budget.c` test
* Add `axirt_budget_isolation.c` test to check manager isolation through AXI-REALM after budget expires (transfer size > budget)
* Further additions: 
* Fix `tclint` version to 0.4.2
* Fix `CHSROOT` to static `realpath` (`pwd` may not be a fully qualified path)
* Check for used features in all non-`helloworld` tests

treewide: Bump AXI-RT and fix AXI-RT functional tests

---

hw/cheshire_pkg.sv

This fixes two errors in the debug module addresses passed to CVA6:
1. `HaltAddress` and `ExceptionAddress` are assumed to be relative to `DmBaseAddress`, see [here](https://github.com/pulp-platform/cva6/blob/99ae53bde1a94b90c1d9bbbe7fe272a9336200a6/core/frontend/frontend.sv#L380) and
[here](https://github.com/pulp-platform/cva6/blob/99ae53bde1a94b90c1d9bbbe7fe272a9336200a6/core/csr_regfile.sv#L2295). In Cheshire, they are currently assigned their absolute address. Coincidentally, this currently does not cause any issues since `AmDbg = '0`,
2. `ExceptionAddress` was changed from `0x808` to `0x810` in https://github.com/pulp-platform/riscv-dbg/pull/145, which is included in the debug module version used in Cheshire. **This means that exceptions in debug mode currently cause CVA6 to jump to …

hw: Fix CVA6 debug module addresses

---

.gitignore
Bender.lock
Bender.yml
cheshire.mk
docs/tg/sim.md
hw/cheshire_pkg.sv
target/sim/src/vip_cheshire_soc.sv
target/sim/vcs/start.cheshire_soc.sh

This required this change:
AXI : https://github.com/pulp-platform/axi/commit/68795181b410406a54247075430f622e22220da3
- __cheshire_pkg.sv__
- VCS: Support for parameter of type 'DefaultMapEntry' inside 'Function' is not yet implemented
- __vip_cheshire_soc.sv__
- `@(negedge rst_n)` is not detected by VCS as `rst_n` is de-asserted at delta 0.
- streams require explicit cast to string
- concatenation of interfaces using `{ }` is not in the standard
TODO:

target/sim: Add VCS simulation flow

---

CHANGELOG.md

For changes, see changelog diff.

CHANGELOG.md: Release v0.2.0

---

sw/tests/axirt_hello.spm.c
sw/tests/helloworld.c

sizeof(char[]) includes the null-terminator.

sw/tests: Do not print null terminators

---

Bender.lock
Bender.yml

Bumps the `axi_rt` dependency to fix minor environment issues (see https://github.com/pulp-platform/axi_rt/pull/22) when including `cheshire.mk` in systems.
Bender automatically bumped minor versions of other dependencies. But I could also isolate the `axi_rt` bump if desired.

deps: Update `axi_rt` to newest version

---

cheshire.mk
hw/cheshire_pkg.sv
hw/cheshire_soc.sv
sw/include/dif/dma.h
sw/lib/crt0.S
sw/tests/axirt_budget.spm.c
sw/tests/axirt_budget_isolate.spm.c
sw/tests/dma_2d.spm.c
sw/tests/spm_uncached.spm.c

Fixes #188.
Changes:
* Add uncached SPM as its own executable region (simplify parameterization a bit in the process)
* Add a test `spm_uncached` executing from uncached SPM and verifying it is not cached
Additional changes:
* Add argument to DMA calls to enable dynamic use of decoupling flags (this breaks DMA API compatibility)
* Add `wfi` to default trap handler (this quiets core on exceptions, including on unhandled `ebreak`)

hw: Fix uncached SPM execute region

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/publish-docs.yml

v2 is broken, see https://github.com/actions/setup-python/issues/1085.

ci: Upgrade setup-python to v5

---

target/sim/src/vip_cheshire_soc.sv

The `vip_cheshire_soc`  module currently allows bursts that are larger than the allowed 4kB in AXI, which triggers some assertions in the `AXI_BUS` interface. The triggered assertions don't really impact functionality, but makes it harder in the CI to check for errors.
I had this problem in picobello, when I preload snitch binaries, which can be quite large (because they contain the entire runtime at the moment).
I only adapted it for writes at the moment, since I don't have a way to test it for large read bursts.

target/sim: Split serial link preload at page boundaries

---

docs/um/sw.md

Current value (2) not consists with value of macro CHESHIRE_BOOT_MODE_BOOT_MODE_VALUE_I2C_24XX1025, which is 3.

doc: Fix boot mode index of I2C EEPROM

---

target/sim/src/elfloader.cpp

This PR enables running the simulation on Windows.
Although it's possible to install all the required dependencies for Cheshire on Windows, the current Makefiles do not provide a way to build the project on Windows directly. Instead, one can use WSL or build on a Linux server and copy the result to a Windows machine. After that, the paths in:
- `target/sim/vsim/compile.cheshire_soc.tcl`,
- `target/sim/vsim/start.cheshire_soc.tcl`
needs to be updated. Once this is done, the simulator can simply be launched and used according to the documentation.
I understand that using Windows in a corporate environment is uncommon, but this approach can be used by enthusiasts and students with an academic license.
If you’d like, I can write instructions for running the simulation on Windows after …

target/sim:  Support non-POSIX systems in `elfloader.cpp`

---

target/sim/src/vip_cheshire_soc.sv

Very minimal commit adding a comment to the `jtag_elf_preload` function, mentioning the requirement that ELF sections be 64b aligned. Preloading otherwise fails with a system bus error, originating from a misaligned access by the DM (`sberror`=3).
As an example where this caused trouble, this function was used in Picobello to preload Snitch's binary, in which sections are 32b-aligned.
Perhaps on a more general note, we could promote the functions in `vip_cheshire_soc` which do not depend on Cheshire (e.g. `jtag_elf_preload`) to `riscv-dbg`, where this function could be extended to support different section alignments. Error messages could also be extended to mention the exact system bus error cause. Let me know if you deem this useful, I could open a PR implementing this.

target/sim: Clarify 64b alignment for `jtag_elf_preload`

---

Bender.lock
Bender.yml
cheshire.mk
docs/um/arch.md
hw/cheshire_pkg.sv
hw/cheshire_soc.sv
sw/tests/clic_smode.spm.S
sw/tests/clic_vsmode.spm.S
target/sim/src/tb_cheshire_pkg.sv
target/xilinx/src/cheshire_top_xilinx.sv

~Maintainer Note: This PR is *stalled* waiting for the following:~
~* Formal release of `v3.0.0` of `clic` (stakeholder: @ezelioli)~
TODO:

treewide: Update CVA6 to `pulp-v2` and add vCLIC support
